---
title: "kidms_data_extraction"
author: "Data Team"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE)
```

```{r}
kidms_user <- Sys.getenv("kidms_user_name")
kidms_pass <- Sys.getenv("kidms_user_passowrd")
dbname <- Sys.getenv("kidms_dbname")
host <- Sys.getenv("kidms_host")
mydb <- dbConnect(MySQL(),
                  user =  kidms_user, 
                  password =  kidms_pass, 
                  
                  dbname = dbname, 
                  host = host)
```
### All samples without storage
```{r}
all_samples <- dbGetQuery(
  mydb,
  "SELECT lsr.`serial_study_id`,lsr.`fk_study`,lsr.time_point,lsr.`specimen_source`,lsr.`date_collect`,lsr.`time_collect`,
lsr.`date_brought`,lsr.`time_brought`,lsr.`date_received`,lsr.`time_received`,lsr.`lab_tech_ini`,
ls.pk_specimen_id,ls.`date_processed`,ls.`time_processed`,spty.type_name
FROM lab_sample_receive lsr    
JOIN lab_specimen ls ON ls.fk_receive_specimen = lsr.id
JOIN lab_specimen_type spty ON spty.id = lsr.fk_specimen_type
WHERE lsr.fk_study = 337
ORDER BY lsr.`date_collect` DESC;
")
```
### Rectal swabs at admission with storage
```{r}
rectal_swabs_kidms_df <- dbGetQuery(
  mydb,
  "SELECT lsr.`serial_study_id`,lsr.`fk_study`, lsr.time_point,lsr.`specimen_source`,lsr.`date_collect`,lsr.`time_collect`,
lsr.`date_brought`,lsr.`time_brought`,lsr.`date_received`,lsr.`time_received`,lsr.`lab_tech_ini`,
ls.pk_specimen_id,ls.`date_processed`,ls.`time_processed`,
spty.type_name,
loc.`media_name` AS freezer, CONCAT_WS(' ',level_prefix,level_name) rack, loc.`slot_level_name` AS slot, loc.`tray_label`, loc.tray box_number, loc.`dimension`, loc.`samp_row`, loc.`samp_column`
FROM lab_sample_receive lsr    
JOIN lab_specimen ls ON ls.fk_receive_specimen = lsr.id
JOIN lab_specimen_type  spty ON  spty.id  = lsr.fk_specimen_type
LEFT JOIN lims.lab_sample_storage_allocation_vw loc ON loc.samp_pk = ls.id
WHERE spty.type_name  ='RECTAL SWAB' 
AND lsr.fk_study = 337")

saveRDS(rectal_swabs_kidms_df, here("data","kidms_samples","rectal_swabs_kidms_df.rds"))
```
###  Community stool 
```{r}
community_stool_kidms_df <- dbGetQuery(
  mydb,
  "SELECT lsr.`serial_study_id`,lsr.id,lsr.`fk_study`,lsr.time_point,lsr.`specimen_source`,lsr.`date_collect`,lsr.`time_collect`,
lsr.`date_brought`,lsr.`time_brought`,lsr.`date_received`,lsr.`time_received`,lsr.`lab_tech_ini`,
ls.pk_specimen_id,ls.`date_processed`,ls.`time_processed`,
spty.type_name,
loc.`media_name` AS freezer, CONCAT_WS(' ',level_prefix,level_name) rack, loc.`slot_level_name` AS slot, loc.`tray_label`, loc.tray box_number, loc.`dimension`, loc.`samp_row`, loc.`samp_column`
FROM lab_sample_receive lsr    
JOIN lab_specimen ls ON ls.fk_receive_specimen = lsr.id
JOIN lab_specimen_type  spty ON  spty.id  = lsr.fk_specimen_type
LEFT JOIN lims.lab_sample_storage_allocation_vw loc ON loc.samp_pk = ls.id
WHERE spty.type_name  ='STOOL' 
AND lsr.fk_study = 337")

saveRDS(community_stool_kidms_df, here("data","kidms_samples","community_stool_kidms_df.rds"))
```

